### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by larsbrinkhoff** [livingcomputermuseum/sImlac#9]
Some way to toggle fullscreen mode, perhaps by pressing F11?

**Comment by livingcomputermuseum** [comment]
Press "Insert" :)

________________________________

**Comment by larsbrinkhoff** [comment]
Great, thanks!

**Comment by larsbrinkhoff** [comment]
Going *back* from fullscreen mode doesn't seem to remove the padding.
